### ISSUE TITLE
Remove aproach to data validation

### ISSUE THREAD

**Issue by fherreazcue** [UoMResearchIT/matlab-novice#16]
There are mentions about whether the data seems fabricated or not... it is not needed and it is distracting... 
We can get rid of those comments, or even regenerate data to make it more "credible"... 

Also, keep only 5 files, so that loops don't take as long to write the list of files.
Note: We could make one file name inconsistent (e.g. 05 instead of 5), so that  it is not as simple?

**Comment by cjfullerton** [comment]
This is largely done, right?

**Comment by fherreazcue** [comment]
Yes, it was resolved in #29 I believe... but we need to still make sure it does not come up in the functions/conditionals episodes...
