### ISSUE TITLE
Update lesson to new carpentries format

### ISSUE THREAD

**Issue by cjfullerton** [UoMResearchIT/matlab-novice#22]
Carpentries lessons are being switched to new format - switch this fork to the new format.

**Comment by fherreazcue** [comment]
Main migration of contents in [c74cbb0](https://github.com/UoMResearchIT/matlab-novice/commit/c74cbb0d826c82390fbf603ef4658573c4991cc2).
Workflows to build contents in [7eeb9af](https://github.com/UoMResearchIT/matlab-novice/commit/7eeb9afcb3ab914bce55820b9432942b73350363).
