### ISSUE TITLE
Typo at End of Arrays

### ISSUE THREAD

**Issue by DrAtbas** [UoMResearchIT/matlab-novice#31]
**Description of the issue**:
Typo at Keypoints.

**Location of the issue**:
It is located at:
https://uomresearchit.github.io/matlab-novice/02-arrays.html
Currently it is in the last keypoints section.

**Current wording**:
E.g. M(5,[3,4,5])”

I think the " at the end is unnecessary.

**Suggested correction**:
E.g. M(5,[3,4,5])

If I'm incorrect, I'm sorry for raising this issue.

**Comment by fherreazcue** [comment]
Fixed in #46
