### ISSUE TITLE
Typo at the end of Plotting Data

### ISSUE THREAD

**Issue by DrAtbas** [UoMResearchIT/matlab-novice#32]
**Description of the issue:**
Typo at Keypoints.

**Location of the issue:**
It is located at:
https://uomresearchit.github.io/matlab-novice/04-plotting.html
Currently it is in the last keypoints section.

**Current wording:**
Use legend and add ,DisplayName="legend name here"

**Suggested correction:**
Use legend and add, DisplayName="legend name here"

**Comment by fherreazcue** [comment]
Fixed in #46
