### ISSUE TITLE
Typo at Writing MATLAB Scripts

### ISSUE THREAD

**Issue by DrAtbas** [UoMResearchIT/matlab-novice#37]
**Description of the issue:**
Typo at Sentences.

**Location of the issue:**
It is located at:
https://uomresearchit.github.io/matlab-novice/05-scripts.html
Currently it is in the 4th paragraph.

**Current wording:**
Matlab will create a file called patient_analysis.m in the src folder. It is important that we let matlab know that we want it to find stuff in this folder. 

**Suggested correction:**
MATLAB will create a file called patient_analysis.m in the src folder. It is important that we let MATLAB know that we want it to find stuff in this folder.

**Comment by fherreazcue** [comment]
Fixed in #46
